CREATE DATABASE destinocerto;
USE destinocerto;

CREATE TABLE CADASTRO (
    NOME VARCHAR (30),
    ID_CADASTRO INTEGER PRIMARY KEY,
    EMAIL VARCHAR (30),
    DATA_NASCIMENTO DATE,
    CPF VARCHAR (15),
    RG VARCHAR (9),
    TELEFONE VARCHAR (11),
    ENDEREÇO VARCHAR (50),
    SENHA VARCHAR (8)
    
);

CREATE TABLE COMPRA (
    VALOR_COMPRA DECIMAL,
    DATA_COMPRA DATE,
    ID_COMPRA INTEGER PRIMARY KEY
    
);

CREATE TABLE DESTINO (
    ID_DESTINO INTEGER PRIMARY KEY,
    LOCAL_DESTINO VARCHAR (15),
    NOME_DESTINO VARCHAR (20)
    
);

CREATE TABLE USUARIO (
    ID_USUARIO INTEGER PRIMARY KEY
    
);

CREATE TABLE PERMISSOES (
    ID_PERMISSAO INTEGER PRIMARY KEY auto_increment,
    TIPO_PERMISSAO VARCHAR (20)
);

CREATE TABLE PASSAGEM (
    ID_PASSAGEM INTEGER PRIMARY KEY,
    NOME_PASSAGEM VARCHAR (20),
    DATA_PASSAGEM DATE
    
);
ALTER TABLE cadastro
ADD COLUMN ID_USUARIO INT;

ALTER TABLE cadastro
ADD FOREIGN KEY (ID_USUARIO)
REFERENCES usuario(ID_USUARIO);

ALTER TABLE compra
ADD COLUMN ID_DESTINO INT;

ALTER TABLE compra
ADD FOREIGN KEY (ID_DESTINO)
REFERENCES destino(ID_DESTINO);

ALTER TABLE destino
ADD COLUMN ID_CADASTRO INT;

ALTER TABLE destino
ADD FOREIGN KEY (ID_CADASTRO)
REFERENCES cadastro(ID_CADASTRO);

ALTER TABLE passagem
ADD COLUMN ID_COMPRA INT;

ALTER TABLE passagem
ADD FOREIGN KEY (ID_COMPRA)
REFERENCES compra(ID_COMPRA);











   


